### PR TITLE
Solution for project euler question #59

### PR DESCRIPTION
**Pull request by bschwagg**
I worked on this at home but figured it would be good to post it in case anyone wants to comment on other ways to solve this, etc.  Normally we solve these in class together.  This was a bit of a test as I'm planning to upload a shot at a lesson plan for using lambas next.

### CODE REVIEW

**Comment by robbintt** [comment]
I am excited to see the lambdas lesson plan!  I'll accept this in a bit.
Eventually we need to find a new organizational method to accommodate
multiple runs at each problem, but it can wait.

Interested in teaching lambdas soon? We are coming up with the plan for
this week. I will still be out of town.

Best,
Trent

On Sunday, February 22, 2015, bschwagg <notifications@github.com> wrote:

> I worked on this at home but figured it would be good to post it in case
> anyone wants to comment on other ways to solve this, etc. Normally we solve
> these in class together. This was a bit of a test as I'm planning to upload
> a shot at a lesson plan for using lambas next.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/PyClass/PyClassLessons/pull/8
> Commit Summary
>
>    - Merge pull request #1 from PyClass/master
>    - A solution to project euler question #59
>
> File Changes
>
>    - *A* projects/project_euler/euler59/convertCsv.py
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-0> (24)
>    - *A* projects/project_euler/euler59/euler59.py
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-1> (66)
>    - *A* projects/project_euler/euler59/euler59_hackerrank.py
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-2> (45)
>    - *A* projects/project_euler/euler59/hackerrank_data.txt
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-3> (2)
>    - *A* projects/project_euler/euler59/test_data.csv
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-4> (1)
>    - *A* projects/project_euler/euler59/test_data.txt
>    <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-5> (2)
>
> Patch Links:
>
>    - https://github.com/PyClass/PyClassLessons/pull/8.patch
>    - https://github.com/PyClass/PyClassLessons/pull/8.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyClass/PyClassLessons/pull/8>.
>


-- 
(Sent from cellphone)

**Comment by bschwagg** [comment]
Hi Trent,

So you're looking for an idea for this Thursday's class when you're out of
town?

I wouldn't mind trying to teach the lambda lesson that day.  I don't claim
to know it as of yet, but I could get a lesson plan set up within the next
couple days.  It would probably be interactive and explore-as-we-go a bit
around a loose structure of ideas to touch.  Sure, just let me know if that
sounds good and I'll start planning it further. I think it would be fun,
even though I'm a bit nervous cause I've never taught anything.

I can't make the Tuesday class though.  By the way.. the main webpage shows
class is still on Tuesday/Thursday. Is that correct or is it switching to
Mondays?

Hope you're having a nice trip
Brad

**Comment by robbintt** [comment]
It will eventually switch to Monday but not yet.  We're getting stable with
tues/thurs then we will evaluate the benefits of switching to Monday one
more time.

I don't want you to feel pressure to rush the class, especially if it will
be your first time teaching something.   It's usually good to read some
teaching guides and whatnot to make sure you are listening and getting
feedback from the audience, although I am sure you have watched a lot of
people teach.

Thursday would be great, but there's the not rushing it aspect of the plan
- Teddy, what do you think? I cc'd you here just in case you aren't getting
these github emails automatically.





Cheers,

Trent Robbins
Tau Informatics LLC
513-233-5651
trent@tauinformatics.com
@trentrobbins

**Comment by robbintt** [comment]
Brad, great if you want to do a lesson! let me know if you want any 
help/feedback before executing, sometimes that helps but sometimes the 
power of going and flowing with it can be spoken to.

IMO lambdas are interesting, and by hearsay, are actually frowned upon 
in production code for many reasons i forget at the moment. still they 
are heavily used in sci-py stack. definitely fun and worth addressing! 
maybe part of the lesson/exercises would be too rewrite some lambda 
statements. one other idea would be to put some links in a readme.md 
file for the class to reference so there isn't time wasted seeing the 
same material. we have regular students with eye issues, (including me), 
and have learned that linking is a time, memory and accessibility issue.

i have an extremely light work week this week so i may continue on with 
pandas or something complimentary and come up with an extra lesson/half 
lesson as a backup for Thursday anyway.

**Comment by bschwagg** [comment]
Hey Trent

Thanks for the ideas and background regarding lambdas, I'll definitely
mention that in the lesson plans, as well as put in links in the readme.md
file and read the info you posted about teaching/socratic method.

I'll shoot to put together a skeleton plan by tomorrow to share with you.
Then I'm off work on Thursday, so I'll have a chance to flush the rest of
it out that morning.

If your backup lesson plans become something you want to teach Thursday,
I'm definitely flexible.  I think it would be a fun experience to give a
shot at a lesson plan, and it also seemed like Thursday's agenda was a TBD
so I'm happy to help out.  Anyways, I'll be ready with the lambdas by then.

Cheers

**Comment by robbintt** [comment]
I believe that was Teddy, cc'ing him.

All that sounds good, I'll leave it in Teddy's hands as I am out of town
for a short while.

Thanks for taking the time to set all this up!

Best,
Trent

On Tuesday, February 24, 2015, bschwagg <notifications@github.com> wrote:

> Hey Trent
>
> Thanks for the ideas and background regarding lambdas, I'll definitely
> mention that in the lesson plans, as well as put in links in the readme.md
> file and read the info you posted about teaching/socratic method.
>
> I'll shoot to put together a skeleton plan by tomorrow to share with you.
> Then I'm off work on Thursday, so I'll have a chance to flush the rest of
> it out that morning.
>
> If your backup lesson plans become something you want to teach Thursday,
> I'm definitely flexible. I think it would be a fun experience to give a
> shot at a lesson plan, and it also seemed like Thursday's agenda was a TBD
> so I'm happy to help out. Anyways, I'll be ready with the lambdas by then.
>
> Cheers
>
> On Mon, Feb 23, 2015 at 5:12 PM, Trent Robbins <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Brad, great if you want to do a lesson! let me know if you want any
> > help/feedback before executing, sometimes that helps but sometimes the
> > power of going and flowing with it can be spoken to.
> >
> > IMO lambdas are interesting, and by hearsay, are actually frowned upon
> > in production code for many reasons i forget at the moment. still they
> > are heavily used in sci-py stack. definitely fun and worth addressing!
> > maybe part of the lesson/exercises would be too rewrite some lambda
> > statements. one other idea would be to put some links in a readme.md
> > file for the class to reference so there isn't time wasted seeing the
> > same material. we have regular students with eye issues, (including me),
> > and have learned that linking is a time, memory and accessibility issue.
> >
> > i have an extremely light work week this week so i may continue on with
> > pandas or something complimentary and come up with an extra lesson/half
> > lesson as a backup for Thursday anyway.
> >
> >
> >
> > On 2/23/15 11:51 AM, Trent Robbins wrote:
> > > It will eventually switch to Monday but not yet. We're getting stable
> > > with tues/thurs then we will evaluate the benefits of switching to
> > > Monday one more time.
> > >
> > > I don't want you to feel pressure to rush the class, especially if it
> > > will be your first time teaching something. It's usually good to read
> > > some teaching guides and whatnot to make sure you are listening and
> > > getting feedback from the audience, although I am sure you have
> > > watched a lot of people teach.
> > >
> > > Thursday would be great, but there's the not rushing it aspect of the
> > > plan - Teddy, what do you think? I cc'd you here just in case you
> > > aren't getting these github emails automatically.
> > >
> > >
> > >
> > >
> > >
> > > Cheers,
> > >
> > > Trent Robbins
> > > Tau Informatics LLC
> > > 513-233-5651 <tel:513-233-5651>
> > > trent@tauinformatics.com
> <javascript:_e(%7B%7D,'cvml','trent@tauinformatics.com');> <mailto:
> trent@tauinformatics.com
> <javascript:_e(%7B%7D,'cvml','trent@tauinformatics.com');>>
> > > @trentrobbins
> > >
> > > On Mon, Feb 23, 2015 at 10:12 AM, bschwagg <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
> > >
> > > Hi Trent,
> > >
> > > So you're looking for an idea for this Thursday's class when
> > > you're out of
> > > town?
> > >
> > > I wouldn't mind trying to teach the lambda lesson that day. I
> > > don't claim
> > > to know it as of yet, but I could get a lesson plan set up within
> > > the next
> > > couple days. It would probably be interactive and explore-as-we-go
> > > a bit
> > > around a loose structure of ideas to touch. Sure, just let me know
> > > if that
> > > sounds good and I'll start planning it further. I think it would
> > > be fun,
> > > even though I'm a bit nervous cause I've never taught anything.
> > >
> > > I can't make the Tuesday class though. By the way.. the main
> > > webpage shows
> > > class is still on Tuesday/Thursday. Is that correct or is it
> > > switching to
> > > Mondays?
> > >
> > > Hope you're having a nice trip
> > > Brad
> > >
> > > On Sun, Feb 22, 2015 at 1:54 PM, Trent Robbins
> > > <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');> <mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>>
> > > wrote:
> > >
> > > > I am excited to see the lambdas lesson plan! I'll accept this in
> > > a bit.
> > > > Eventually we need to find a new organizational method to
> > > accommodate
> > > > multiple runs at each problem, but it can wait.
> > > >
> > > > Interested in teaching lambdas soon? We are coming up with the
> > > plan for
> > > > this week. I will still be out of town.
> > > >
> > > > Best,
> > > > Trent
> > > >
> > > > On Sunday, February 22, 2015, bschwagg <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
> > > >
> > > > > I worked on this at home but figured it would be good to post
> > > it in case
> > > > > anyone wants to comment on other ways to solve this, etc.
> > > Normally we
> > > > solve
> > > > > these in class together. This was a bit of a test as I'm
> > > planning to
> > > > upload
> > > > > a shot at a lesson plan for using lambas next.
> > > > > ------------------------------
> > > > > You can view, comment on, or merge this pull request online at:
> > > > >
> > > > > https://github.com/PyClass/PyClassLessons/pull/8
> > > > > Commit Summary
> > > > >
> > > > > - Merge pull request #1 from PyClass/master
> > > > > - A solution to project euler question #59
> > > > >
> > > > > File Changes
> > > > >
> > > > > - *A* projects/project_euler/euler59/convertCsv.py
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-0> (24)
> > > > > - *A* projects/project_euler/euler59/euler59.py
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-1> (66)
> > > > > - *A* projects/project_euler/euler59/euler59_hackerrank.py
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-2> (45)
> > > > > - *A* projects/project_euler/euler59/hackerrank_data.txt
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-3> (2)
> > > > > - *A* projects/project_euler/euler59/test_data.csv
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-4> (1)
> > > > > - *A* projects/project_euler/euler59/test_data.txt
> > > > >
> > > <https://github.com/PyClass/PyClassLessons/pull/8/files#diff-5> (2)
> > > > >
> > > > > Patch Links:
> > > > >
> > > > > - https://github.com/PyClass/PyClassLessons/pull/8.patch
> > > > > - https://github.com/PyClass/PyClassLessons/pull/8.diff
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/PyClass/PyClassLessons/pull/8>.
> > > > >
> > > >
> > > >
> > > > --
> > > > (Sent from cellphone)
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > <
> https://github.com/PyClass/PyClassLessons/pull/8#issuecomment-75464948
> > >.
> > >
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/PyClass/PyClassLessons/pull/8#issuecomment-75598173
> > >.
> > >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PyClass/PyClassLessons/pull/8#issuecomment-75679665
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyClass/PyClassLessons/pull/8#issuecomment-75819103>.
>


-- 
(Sent from cellphone)

**Comment by teddymcw** [comment]
ya that was me, but flattered you thought i was Trent :)

let me know if you are or aren't ready for a portion or full class 
period on Thursday, partly so i can know what to expect and how to be 
prepared for a productive two hours, i'm sure we'll be all good tho

**Comment by bschwagg** [comment]
Hi Teddy
Ok, will do..
I have the day off work and am currently working on the lesson at Noisebridge..
I'm shooting to send a pull request for it by this evening, so you can take a look at the lesson and gauge it's length or want to add/edit anything. There's definitely not as much material as flask or django, so it's more of just a fun use of python.  I'm trying to keep it relevant and useful though.

**Pull request merged**
